name: SendLog
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
targets:
  SendLog:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SendLog
        excludes:
          - Resources/Info.plist
    info:
      path: SendLog/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SendLog
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: Import wall photos to build and save boulder problems offline.
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: Save exported wall images and backups from SendLog.
        DEVELOPMENT_TEAM: ""
